local opts = { -- Useful plugin to show you pending keybinds.
  'folke/which-key.nvim',
  version = 'v3.17.0',
  config = function() -- This is the function that runs, AFTER loading
    local wk = require 'which-key'
    wk.setup()

    -- Document existing key chains
    wk.add {
      { '<leader>a', group = '[A]rtificial Intelligence', mode = { 'n', 'v' } },
      { '<leader>l', group = '[L]sp' },
      { '<leader>lt', group = '[T]oggle' },
      { '<leader>lw', group = '[W]orkspace' },
      { '<leader>lh', group = '[H]ierarchy' },
      { '<leader>le', group = '[E]lixir' },
      { '<leader>d', group = '[D]iagnostics' },
      { '<leader>s', group = '[S]elect', mode = { 'v' } },
      { '<leader>n', group = '[N]otification' },
      { '<leader>r', group = '[R]sync' },
      { '<leader>ru', group = '[U]pload' },
      { '<leader>rd', group = '[D]ownload' },
      { '<leader>rc', group = '[C]onfig' },
      { '<leader>sm', group = '[M]ulti-cursor', mode = { 'n', 'v' } },
      { '<leader>sq', group = '[Q]uickfix' },
      { '<leader>st', group = '[T]odo' },
      { '<leader>sc', group = '[C]ommands' },
      { '<leader>w', group = '[W]orkspace' },
      { '<leader>ws', group = '[s]ession' },
      { '<leader>wm', group = '[m]anagement' },
      { '<leader>wms', group = '[s]plit' },
      { '<leader>q', group = 'quickfix / trouble / location list' },
      { '<leader>qt', group = 'trouble' },
      { '<leader>ql', group = 'location list' },
      { '<leader>qT', group = 'Todo' },
      { '<leader>h', group = 'Grapple' },
      { '<leader>m', group = '[m]ini.nvim', mode = { 'n', 'v' } },
      { '<leader>ms', group = '[M]ini [S]urround', mode = { 'n', 'v' } },
      { '<leader>g', group = 'Git', mode = { 'n', 'v' } },
      { '<leader>gs', group = 'Search', mode = { 'n', 'v' } },
      { '<leader>gh', group = 'Hunk/Buffer', mode = { 'n', 'v' } },
      { '<leader>gt', group = '[T]oggle' },
      { '<leader>t', group = '[T]est' },
      { '<leader>p', group = 'Command [P]alette' },
      { '<leader>td', group = '[D]ebug test' },
      { '<leader>f', group = '[F]ile', mode = { 'n', 'v' } },
      { '<leader>fy', group = '[Y]azi', mode = { 'n', 'v' } },
      { '<leader>b', group = '[B]uffer', mode = { 'n', 'v' } },
      { '<leader>bc', group = '[C]omment', mode = { 'n', 'v' } },
      { '<leader>bca', group = 'Arrange-Act-Assert', mode = { 'n', 'v' } },
      { '<leader>bo', group = '[O]rder [B]uffer', mode = { 'n', 'v' } },
      { '<leader>b6', group = '[B]ase64', mode = { 'n', 'v' } },
      { '<leader>ba', group = '[a]ll [b]uffers' },
      { '<leader>by', group = '[y]ank' },
      { '<leader>v', group = '[v]isual motions', mode = { 'n', 'v' } },
      { '<leader>vt', group = '[t]reesitter' },
    }
  end,
}

return opts
