local opts = { -- Useful plugin to show you pending keybinds.
  'folke/which-key.nvim',
  version = 'v3.17.0',
  config = function() -- This is the function that runs, AFTER loading
    local wk = require 'which-key'
    wk.setup()

    -- Document existing key chains
    wk.add {
      { '<leader>a', group = '[A]rtificial Intelligence', mode = { 'n', 'v' }, icon = '' },
      { '<leader>ao', group = '[O]pen AI Codex', mode = { 'n', 'v' }, icon = '' },
      { '<leader>l', group = '[L]sp', icon = '󰅩' },
      { '<leader>lt', group = '[T]oggle', icon = '󰔢' },
      { '<leader>lw', group = '[W]orkspace', icon = '󱂬' },
      { '<leader>lh', group = '[H]ierarchy', icon = '󰓍' },
      { '<leader>le', group = '[E]lixir', icon = '' },
      { '<leader>s', group = '[S]elect', mode = { 'v' }, icon = '󰩭' },
      { '<leader>s', group = '[S]earch', mode = { 'n' }, icon = '' },
      { '<leader>n', group = '[N]otification', icon = '󰎟' },
      { '<leader>r', group = '[R]sync', icon = '' },
      { '<leader>ru', group = '[U]pload', icon = '󰕒' },
      { '<leader>rd', group = '[D]ownload', icon = '󰇚' },
      { '<leader>rc', group = '[C]onfig', icon = '' },
      { '<leader>sm', group = '[M]ulti-cursor', mode = { 'n', 'v' } },
      { '<leader>sq', group = '[Q]uickfix', icon = '󰁨' },
      { '<leader>st', group = '[T]odo', icon = '' },
      { '<leader>sc', group = '[C]ommands', icon = '' },
      { '<leader>w', group = '[W]orkspace', icon = '󱂬' },
      { '<leader>ws', group = '[s]ession', icon = '󰆔' },
      { '<leader>wm', group = '[m]anagement', icon = '' },
      { '<leader>wms', group = '[s]plit', icon = '󱤗' },
      { '<leader>q', group = 'quickfix / trouble / location list', icon = '󰁨' },
      { '<leader>qt', group = 'trouble', icon = '' },
      { '<leader>ql', group = 'location list' },
      { '<leader>qT', group = '[T]odo', icon = '' },
      { '<leader>h', group = 'Grapple', icon = '' },
      { '<leader>m', group = '[m]ini.nvim', mode = { 'n', 'v' }, icon = '' },
      { '<leader>ms', group = '[M]ini [S]urround', mode = { 'n', 'v' } },
      { '<leader>g', group = '[G]it', mode = { 'n', 'v' }, icon = '' },
      { '<leader>gs', group = 'Search', mode = { 'n', 'v' }, icon = '' },
      { '<leader>gh', group = 'Hunk/Buffer', mode = { 'n', 'v' }, icon = '' },
      { '<leader>gt', group = '[T]oggle', icon = '󰔢' },
      { '<leader>t', group = '[T]est', icon = '󰙨' },
      { '<leader>td', group = '[D]ebug test', icon = '' },
      { '<leader>p', group = 'Command [P]alette', icon = '' },
      { '<leader>f', group = '[F]ile', mode = { 'n', 'v' }, icon = '󰈞' },
      { '<leader>fy', group = '[Y]azi', mode = { 'n', 'v' }, icon = '' },
      { '<leader>b', group = '[B]uffer', mode = { 'n', 'v' }, icon = '' },
      { '<leader>bc', group = '[C]omment', mode = { 'n', 'v' }, icon = '󰅺' },
      { '<leader>bca', group = 'Arrange-Act-Assert', mode = { 'n', 'v' }, icon = '' },
      { '<leader>bo', group = '[O]rder [B]uffer', mode = { 'n', 'v' }, icon = '󰈍' },
      { '<leader>b6', group = '[B]ase64', mode = { 'n', 'v' } },
      { '<leader>ba', group = '[a]ll [b]uffers', icon = '' },
      { '<leader>by', group = '[y]ank', icon = '' },
      { '<leader>v', group = '[v]isual motions', mode = { 'n', 'v' }, icon = '' },
      { '<leader>vt', group = '[t]reesitter', icon = '󱏒' },
    }
  end,
}

return opts
